spring:
  boot:
    admin:
      client:
        url: http://localhost:9096
        username: admin
        password: 123
        instance:
          prefer-ip: true
          metadata:
            management:
              port: 8081
            user:
              name: actuator
              password: 123
  application:
    name: "API de Mensagens"
  datasource:
    url: jdbc:mysql://localhost:3306/demomensagens?createDatabaseIfNotExist=true&verifyServerCertificate=false&connectionTimeZone=UTC
    username: root
    password: password
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      "[hibernate.generate_statistics]": true
  profiles:
    active: 
      - dev
      - jpa

server:
  port: 8080

integracao:
  api:
    localidades:
      url: 'http://localhost:3001'
      paises-path: '/paises'
      
management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      #base-path: "/gerenciador"
      #path-mapping:
        #health: "saude"
        #metrics: "metricas"
      exposure:
        include: "metrics,health,info,auditevents,usuarios,loggers"
    jmx:
      exposure:
        include: "metrics"
  metrics:
    enable:
      executor.active: false # para deativar uma metrica
  health:
    diskspace:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: when-authorized
      roles: 'ACTUATOR'
    metrics:
      enabled: true
    info:
      enabled: true
    auditevents:
      enabled: true
    loggers:
      enabled: true

info:
  application:
    nome: ${spring.application.name}
    descricao: API de mensagens com simples demonstração de uso de Spring Boot
      
    